name: PR
on:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run PR script
              run: |
                  npm ci
                  npm run pr
                  [[ -z $(git status -s) ]]
