name: PR
on:
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - run: npm ci
            - run: npm run build
            - run: npm run pr
            - name: Check no changes
              run: |
                  git status -s
                  [[ -z $(git status -s) ]]
